### ISSUE TITLE
プロフィール画像

### ISSUE THREAD

**Issue by stivan622** [fitness-app/fitness_app#14]
# TODO
- [x] Gem carrier wave 導入
- [x] 機能実装 (Usersテーブルのavatorカラム）（カラムは作成済み）
- [x] 画像のサイズの統一(アイコンサイズ）やり方複数あるのでは提案してください

参考
https://diveintocode.jp/diver/curriculums/33

**Comment by stivan622** [comment]
gemを追加
```
gem 'carrierwave'
gem 'rmagick'
```

**Comment by stivan622** [comment]
`avatar_uploader.rb`に命名しましたー

**Comment by stivan622** [comment]
参考になる
http://www.workabroad.jp/tech/1118

**Comment by stivan622** [comment]
```
uninitialized constant User::AvatarUploader
```
いきなり詰まる

**Comment by stivan622** [comment]
理由はわからないが解決
http://qiita.com/h5y1m141@github/items/97e1941086c7f9f229ac

**Comment by stivan622** [comment]
キタ!!
![2016-10-14 15 55 18](https://cloud.githubusercontent.com/assets/20553255/19378270/a40baf64-9226-11e6-9597-82d13b971de0.png)

**Comment by stivan622** [comment]
編集がうまくいかない

**Comment by stivan622** [comment]
プロフィール更新に成功したが
Current passwordが発火してしまう問題
↑後回し

画像サイズ問題はヘルパー作成でいきます

**Comment by stivan622** [comment]
アイコン表示のメソッド作りました
ヘルパーメソッドなのでどのviewファイルでもつかます
`user`にユーザデータを入れてあげてください

```
  def profile_icon(`user`)
    unless user.avatar.blank?
      img_url = user.avatar
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name, size: '45x45')
  end
```

**Comment by stivan622** [comment]
バリデーション設定done
